import Foundation
func run_tests() {
    print("Board Tests\n")
    let three_by_three_board_test = ThreeByThreeSpec()
    three_by_three_board_test.test_init_board()
    three_by_three_board_test.test_check_win_blank()
    three_by_three_board_test.test_check_win_rows()
    three_by_three_board_test.test_check_win_cols()
    three_by_three_board_test.test_check_win_diags()
    let universal_board_test = UniversalBoardSpec()
    print("--------------------")
    print("\nUniversal Board Tests")
    universal_board_test.test_is_empty()
    universal_board_test.return_winner_test()
    universal_board_test.test_is_full()
    universal_board_test.game_over_test()
    print("--------------------")
    print("\nGameMaster")
    let game_master_test = GameMasterSpec()
    game_master_test.test_switch_player()
    game_master_test.test_place_move_0()
    game_master_test.test_place_move_4()
    game_master_test.test_place_move_multiple()
    game_master_test.test_valid_move()
    print("--------------------")
    print("\nAi Tests")
    print("--------------------")
    let ai_test = AiSpec()
    print("\nAi is X")
    ai_test.test_chooses_to_win_x()
    ai_test.test_chooses_to_draw_when_no_win_x()
    ai_test.test_chooses_fast_win_x()
    print("--------------------")
    print("\nAi is O")
    ai_test.test_chooses_to_win_o()
    ai_test.test_chooses_to_draw_when_no_win_o()
    ai_test.test_chooses_fast_win_o()
    print("--------------------")
    print("\nTerminal Input Tests")
    let terminal_input_test = TerminalInputSpec()
    terminal_input_test.test_get_move_empty_board()
    terminal_input_test.test_get_move_spot_taken()
    terminal_input_test.test_get_move_is_not_whole()
    terminal_input_test.test_get_move_is_not_a_number()
    terminal_input_test.test_get_move_is_out_of_bounds()
    terminal_input_test.test_get_player_valid_choice_x()
    terminal_input_test.test_get_player_valid_choice_X()
    terminal_input_test.test_get_player_valid_choice_o()
    terminal_input_test.test_get_player_valid_choice_O()
    terminal_input_test.test_get_player_invalid_choices()
    print("--------------------")
    print("\nTerminal Display Tests")
    let terminal_display_test = TerminalDisplaySpec()
    terminal_display_test.test_display_empty()
    terminal_display_test.test_display_players()
    terminal_display_test.test_display_ai_turn()
    terminal_display_test.test_display_human_turn()
    terminal_display_test.test_display_invalid_move()
    terminal_display_test.test_display_invalid_player()
    terminal_display_test.test_display_start_message()
    terminal_display_test.test_display_choose_player()
    terminal_display_test.test_display_winning_message_X()
    terminal_display_test.test_display_winning_message_O()
    terminal_display_test.test_display_winning_message_C()
    print("--------------------")
    print("\nHuman Vs Ai Tests")
    let game_test = HumanVsAiSpec()
    game_test.test_play_game_starts_empty()
    game_test.test_play_game_first_move()
    game_test.test_play_game_displays_turn_messages()
    game_test.test_play_game_ai_makes_move()
    game_test.test_play_game_human_makes_invalid_move()
    game_test.test_play_game_winner()
}
run_tests()
